// Sample data for the "Load sample data" button in the admin panel.
// genId is passed in so ids are generated the same way as everything else.
export function buildSeed(genId) {
  const [c1, c2, c3, c4, c5, c6, c7, c8] = Array.from({ length: 8 }, () => genId());

  const campaigns = [
    {
      id: c1,
      title: "Independence Day Celebration",
      description: "Flag hoisting, milli naghmay, and refreshments for 14 August.",
      goal: 60000,
      accountType: "JazzCash",
      accountNumber: "0300-1234567",
      accountTitle: "Bilal Ahmed",
      venue: "Main Ground",
      eventDate: "2026-08-14T08:00",
      theme: "independence",
      images: [],
      closed: false,
      createdAt: Date.now() - 86400000 * 6,
    },
    {
      id: c2,
      title: "Milad-un-Nabi Mehfil",
      description: "Naat khwani, decoration, and langar for the Milad gathering.",
      goal: 35000,
      accountType: "Easypaisa",
      accountNumber: "0321-5551234",
      accountTitle: "Sara Malik",
      venue: "Central Mosque Hall",
      eventDate: "2026-09-05T19:00",
      theme: "milad",
      images: [],
      closed: false,
      createdAt: Date.now() - 86400000 * 5,
    },
    {
      id: c3,
      title: "Spring Convocation Fund",
      description: "Covering stage, sound, and refreshments for the convocation ceremony.",
      goal: 80000,
      accountType: "HBL",
      accountNumber: "PK00HABB0001234567890",
      accountTitle: "University Society Account",
      venue: "Main Auditorium",
      eventDate: "2026-09-20T09:00",
      theme: "convocation",
      images: [],
      closed: false,
      createdAt: Date.now() - 86400000 * 4,
    },
    {
      id: c4,
      title: "Inter-Department Sports Gala",
      description: "Kits, trophies, and refreshments for the annual sports gala.",
      goal: 70000,
      accountType: "JazzCash",
      accountNumber: "0345-7778899",
      accountTitle: "Usman Raza",
      venue: "University Sports Complex",
      eventDate: "2026-10-02T08:00",
      theme: "sports",
      images: [],
      closed: false,
      createdAt: Date.now() - 86400000 * 3,
    },
    {
      id: c5,
      title: "Cultural Mela",
      description: "Stalls, stage decor, and prizes for the annual cultural mela.",
      goal: 55000,
      accountType: "Easypaisa",
      accountNumber: "0333-2223344",
      accountTitle: "Zainab Ali",
      venue: "Student Plaza",
      eventDate: "2026-10-10T11:00",
      theme: "cultural",
      images: [],
      closed: false,
      createdAt: Date.now() - 86400000 * 2,
    },
    {
      id: c6,
      title: "Flood Relief Drive",
      description: "Ration packs and essentials for flood-affected families.",
      goal: 100000,
      accountType: "Bank Transfer",
      accountNumber: "PK00MEZN0009876543210",
      accountTitle: "Campus Welfare Society",
      venue: "Collection desk, Block A",
      eventDate: "2026-08-28T10:00",
      theme: "charity",
      images: [],
      closed: false,
      createdAt: Date.now() - 86400000 * 7,
    },
    {
      id: c7,
      title: "Final Year Farewell Dinner",
      description: "Venue, catering, and mementos for the graduating batch's farewell.",
      goal: 90000,
      accountType: "JazzCash",
      accountNumber: "0300-4445566",
      accountTitle: "Hamza Tariq",
      venue: "Banquet Hall, Student Centre",
      eventDate: "2026-11-15T18:00",
      theme: "farewell",
      images: [],
      closed: false,
      createdAt: Date.now() - 86400000,
    },
    {
      id: c8,
      title: "CS Society Trip",
      description: "Bus and entry tickets for the department's industry visit.",
      goal: 40000,
      accountType: "Easypaisa",
      accountNumber: "0333-9876543",
      accountTitle: "Sara Malik",
      venue: "Departs from Block C gate",
      eventDate: "2026-09-25T08:00",
      theme: "general",
      images: [],
      closed: false,
      createdAt: Date.now() - 86400000,
    },
  ];

  const donations = [
    { id: genId(), campaignId: c1, donorName: "Ayesha Khan", department: "Computer Science", programme: "BS(CS) 2023", amount: 1000, ref: "TXN00123456", createdAt: Date.now() - 70000000 },
    { id: genId(), campaignId: c1, donorName: "Hamza Tariq", department: "Software Engineering", programme: "BS(SE) 2022", amount: 500, ref: "TXN00123999", createdAt: Date.now() - 60000000 },
    { id: genId(), campaignId: c1, donorName: "Fatima Noor", department: "Computer Science", programme: "BS(CS) 2024", amount: 2000, ref: "", createdAt: Date.now() - 3000000 },
    { id: genId(), campaignId: c2, donorName: "Usman Raza", department: "Electrical Engineering", programme: "BS(EE) 2023", amount: 300, ref: "TXN00111222", createdAt: Date.now() - 90000000 },
    { id: genId(), campaignId: c3, donorName: "Zainab Ali", department: "Computer Science", programme: "BS(CS) 2023", amount: 1500, ref: "TXN00445566", createdAt: Date.now() - 20000000 },
    { id: genId(), campaignId: c4, donorName: "Bilal Ahmed", department: "Computer Science", programme: "BS(CS) 2022", amount: 800, ref: "", createdAt: Date.now() - 1000000 },
    { id: genId(), campaignId: c6, donorName: "Sara Malik", department: "Business Administration", programme: "BBA 2023", amount: 2500, ref: "TXN00998877", createdAt: Date.now() - 40000000 },
  ];

  return { campaigns, donations };
}
